# Generated by Django 6.1 on 2026-08-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), (
                'CANCELLED', 'Cancelada'), ('RETURNED', 'Devuelta')], default='PENDING', max_length=20),
        ),
    ]
