# Generated by Django 6.1 on 2026-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='UNKNOWN'),
            preserve_default=False,
        ),
    ]
