# Generated by Django 6.1 on 2026-08-31 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventorymovement_order_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venta'), (
                'ADJUSTMENT', 'Ajuste')], default='ADJUSTMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='products', to='products.supplier'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='inventory_movements', to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='inventory_movements', to='products.supplier'),
        ),
    ]
